// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Upgrade:                              1
// Endpoints:                            8
// Async Callback (empty):               1
// Total number of exported functions:  11

#![no_std]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    arcade_game
    (
        init => init
        upgrade => upgrade
        recordAction => record_action
        setHandle => set_handle
        getLeaderboard => get_leaderboard
        getPlayerCount => get_player_count
        getPlayerEntry => get_player_entry
        getGlobalActions => get_global_actions
        getGameId => get_game_id
        getSessionWindowMs => get_session_window_ms
    )
}

multiversx_sc_wasm_adapter::async_callback_empty! {}
