// Code generated by the multiversx-sc proxy generator. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

#![allow(dead_code)]
#![allow(clippy::all)]

use multiversx_sc::proxy_imports::*;

pub struct ArcadeGameProxy;

impl<Env, From, To, Gas> TxProxyTrait<Env, From, To, Gas> for ArcadeGameProxy
where
    Env: TxEnv,
    From: TxFrom<Env>,
    To: TxTo<Env>,
    Gas: TxGas<Env>,
{
    type TxProxyMethods = ArcadeGameProxyMethods<Env, From, To, Gas>;

    fn proxy_methods(self, tx: Tx<Env, From, To, (), Gas, (), ()>) -> Self::TxProxyMethods {
        ArcadeGameProxyMethods { wrapped_tx: tx }
    }
}

pub struct ArcadeGameProxyMethods<Env, From, To, Gas>
where
    Env: TxEnv,
    From: TxFrom<Env>,
    To: TxTo<Env>,
    Gas: TxGas<Env>,
{
    wrapped_tx: Tx<Env, From, To, (), Gas, (), ()>,
}

#[rustfmt::skip]
impl<Env, From, Gas> ArcadeGameProxyMethods<Env, From, (), Gas>
where
    Env: TxEnv,
    Env::Api: VMApi,
    From: TxFrom<Env>,
    Gas: TxGas<Env>,
{
    /// Deploy-time config. 
    /// - `game_id`: a short id for this game (e.g. "nova-taps"), emitted (indexed) 
    ///   on every `arcadeAction` event so the hub can group actions by game. 
    /// - `session_window_ms`: the rolling window for scoring, in MILLISECONDS. Pass 
    ///   0 for the 30s default. A short window = a timed sprint; a very large window 
    ///   = an all-time cumulative count. 
    pub fn init<
        Arg0: ProxyArg<ManagedBuffer<Env::Api>>,
        Arg1: ProxyArg<u64>,
    >(
        self,
        game_id: Arg0,
        session_window_ms: Arg1,
    ) -> TxTypedDeploy<Env, From, NotPayable, Gas, ()> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_deploy()
            .argument(&game_id)
            .argument(&session_window_ms)
            .original_result()
    }
}

#[rustfmt::skip]
impl<Env, From, To, Gas> ArcadeGameProxyMethods<Env, From, To, Gas>
where
    Env: TxEnv,
    Env::Api: VMApi,
    From: TxFrom<Env>,
    To: TxTo<Env>,
    Gas: TxGas<Env>,
{
    /// Storage persists across upgrades. `game_id` and the window keep their stored 
    /// values unless you explicitly re-set them here. 
    pub fn upgrade(
        self,
    ) -> TxTypedUpgrade<Env, From, To, NotPayable, Gas, ()> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_upgrade()
            .original_result()
    }
}

#[rustfmt::skip]
impl<Env, From, To, Gas> ArcadeGameProxyMethods<Env, From, To, Gas>
where
    Env: TxEnv,
    Env::Api: VMApi,
    From: TxFrom<Env>,
    To: TxTo<Env>,
    Gas: TxGas<Env>,
{
    /// Record one real action. Takes NO arguments, so the score cannot be 
    /// self-reported: it is +1 to the caller's current session, and the best 
    /// session a caller ever lands is their leaderboard score. Opens a fresh 
    /// session if the last action was more than `session_window_ms` ago. Always 
    /// bumps the global counter and emits `arcadeAction`. 
    ///  
    /// There is nothing to rate-limit or bound here. A player (or a bot) can only 
    /// raise their score by sending more real transactions, which is exactly the 
    /// onchain activity the Arcade is proving. 
    pub fn record_action(
        self,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, ()> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("recordAction")
            .original_result()
    }

    /// Attach a username to the caller's address, shown next to their score. A real 
    /// score is required first, so a handle can't be claimed without playing. 
    pub fn set_handle<
        Arg0: ProxyArg<ManagedBuffer<Env::Api>>,
    >(
        self,
        handle: Arg0,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, ()> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("setHandle")
            .argument(&handle)
            .original_result()
    }

    /// Every entry on the board, UNSORTED. The reader sorts client-side (by score 
    /// descending, ties broken by earlier timestamp). Returning the raw set keeps 
    /// reads cheap and lets the board grow without an onchain sort cap. Cost scales 
    /// with the player count; for a very large board, page with the player set. 
    pub fn get_leaderboard(
        self,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, MultiValueEncoded<Env::Api, ScoreEntry<Env::Api>>> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("getLeaderboard")
            .original_result()
    }

    /// Number of distinct players with a score on the board. 
    pub fn get_player_count(
        self,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, usize> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("getPlayerCount")
            .original_result()
    }

    /// A single player's entry, or an empty entry (score 0) if they've never 
    /// scored. Lets the UI show "your rank/score" cheaply. 
    pub fn get_player_entry<
        Arg0: ProxyArg<ManagedAddress<Env::Api>>,
    >(
        self,
        address: Arg0,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, ScoreEntry<Env::Api>> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("getPlayerEntry")
            .argument(&address)
            .original_result()
    }

    /// This game's global running total of onchain actions. The hub reads this from 
    /// every featured game and sums to a single cross-game odometer (no indexer 
    /// needed). For an event-driven hub, sum the `arcadeAction` events instead — 
    /// both give the same total. 
    pub fn get_global_actions(
        self,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, u64> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("getGlobalActions")
            .original_result()
    }

    /// The game id set at deploy. 
    pub fn get_game_id(
        self,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, ManagedBuffer<Env::Api>> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("getGameId")
            .original_result()
    }

    /// The configured session window in milliseconds. 
    pub fn get_session_window_ms(
        self,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, u64> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("getSessionWindowMs")
            .original_result()
    }
}

#[type_abi]
#[derive(TopEncode, TopDecode, NestedEncode, NestedDecode, ManagedVecItem, Clone, PartialEq, Eq, Debug)]
pub struct ScoreEntry<Api>
where
    Api: ManagedTypeApi,
{
    pub address: ManagedAddress<Api>,
    pub handle: ManagedBuffer<Api>,
    pub score: u64,
    pub timestamp: u64,
}
